name: lora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  google_fonts: ^6.2.1
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  get_it: ^8.0.1
  fl_chart: ^0.69.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  firebase_messaging: ^15.1.3
  flutter_easyloading: ^3.0.5
  razorpay_flutter: ^1.3.7
  file_picker: ^8.1.3
  scratcher: ^2.5.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
